### ISSUE TITLE
[Bug] Tabs don't close in accordion layout

### ISSUE THREAD

**Issue by hastinbe** [stellarwp/kadence-blocks#268]
Version: 3.0.10

When changing the active tab in accordion layout the other tabs don't close. Unsure if this is an intentional change, but the behavior is different from 2.x

Thanks for the release!

**Comment by kadencewp** [comment]
This should have been the behavior in 2.x 

I just tested to confirm it was the behavior in 2.x

In mobile large accordions that auto close create an awful experience on a phone because the size of the page changes, which causes the user to lose their place. Since tabs generally have larger content than accordions it was set up this way on purpose.

**Comment by hastinbe** [comment]
We don't mind the difference, some of our users do, and we agree with your assessment. I'll close this, not sure why the behavior of ours is different, it actually closes the other open tab and scrolls to the newly opened one. In any case I'll close this as apparently there's nothing to fix here.

**Comment by kadencewp** [comment]
Can you send a link? the accordion block works this way but tabs don't. Perhaps there is something else at play

**Comment by hastinbe** [comment]
I checked, my mistake it was the beta 3.x that did it not 2.x, I forgot we were running that on our production server
